# Generated by Django 3.2.6 on 2022-07-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220730_2108'),
    ]

    operations = [

    ]
