# Generated by Django 3.2.13 on 2022-07-30 15:32

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ceremony_datetime',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Iran', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
